name: Docker Build

on:
  workflow_dispatch:

  push:
    branches: main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Github Docker Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REPO_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./linkwarden
          file: ./linkwarden/Dockerfile
          platforms: linux/amd64,linux/arm64
          build-args: NEXT_PUBLIC_EMAIL_PROVIDER=true
          push: true
          tags: ghcr.io/apocalypsor/linkwarden:latest
