name: Update

on:
  workflow_dispatch:
  
  push:
    branches:
      - main
    paths:
      - .github/workflows/update.yaml
  
  schedule:
    - cron: 0 4 * * *

jobs:
  Update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.REPO_TOKEN }}
          fetch-depth: 0
          submodules: true
      - name: Update Submodules
        run: |
          git submodule foreach --recursive '
            git fetch origin --tags --force  # Ensure tags are fetched
            git checkout --quiet $(git describe --tags --abbrev=0 origin)  # Checkout most recent release tag
            git submodule update --init --recursive  # Initialize any new submodules
            git clean -dfx  # Remove untracked files
          '
      - name: Push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update Linkwarden
          skip_dirty_check: false
          commit_user_name: Action Bot
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
          commit_author: Action <actions@github.com>
